-- Universal Job Finder — database schema
-- Run this once in Supabase: SQL Editor -> New query -> paste -> Run.
--
-- Row Level Security is what makes the public anon key safe. Every policy below
-- checks auth.uid() against the row's user_id, so a signed-in visitor can only
-- ever read or write their own rows, no matter what they send from the browser.

-- ---------------------------------------------------------------- applications
create table if not exists public.applications (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  role        text not null,
  company     text,
  loc         text,
  platform    text,
  pay         text,
  url         text,
  status      text not null default 'Saved',
  date        date  not null default current_date,
  created_at  timestamptz not null default now(),
  constraint status_allowed check (
    status in ('Saved','Applied','Screening','Interviewing','Offer','Closed')
  )
);

create index if not exists applications_user_created_idx
  on public.applications (user_id, created_at desc);

alter table public.applications enable row level security;

drop policy if exists "own rows: read"   on public.applications;
drop policy if exists "own rows: insert" on public.applications;
drop policy if exists "own rows: update" on public.applications;
drop policy if exists "own rows: delete" on public.applications;

create policy "own rows: read"   on public.applications
  for select using (auth.uid() = user_id);
create policy "own rows: insert" on public.applications
  for insert with check (auth.uid() = user_id);
create policy "own rows: update" on public.applications
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own rows: delete" on public.applications
  for delete using (auth.uid() = user_id);

-- If you already ran an earlier version of this file, add the new column:
--   alter table public.applications add column if not exists url text;

-- ------------------------------------------------------------------- profiles
-- The resume-derived profile only: title, field, skills, matched roles.
-- The resume file itself is never stored.
create table if not exists public.profiles (
  user_id     uuid primary key references auth.users (id) on delete cascade,
  profile     jsonb not null,
  updated_at  timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "own profile: read"   on public.profiles;
drop policy if exists "own profile: write"  on public.profiles;
drop policy if exists "own profile: update" on public.profiles;
drop policy if exists "own profile: delete" on public.profiles;

create policy "own profile: read"   on public.profiles
  for select using (auth.uid() = user_id);
create policy "own profile: write"  on public.profiles
  for insert with check (auth.uid() = user_id);
create policy "own profile: update" on public.profiles
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own profile: delete" on public.profiles
  for delete using (auth.uid() = user_id);

-- --------------------------------------------------------- account deletion
-- Lets a signed-in person erase everything you hold about them, which most
-- privacy regimes require you to offer. Call from the client:
--   await sb.rpc('delete_my_data')
create or replace function public.delete_my_data()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.applications where user_id = auth.uid();
  delete from public.profiles     where user_id = auth.uid();
end;
$$;

revoke all on function public.delete_my_data() from public;
grant execute on function public.delete_my_data() to authenticated;
